// Type augmentation for the `signal_dispatches` table.
//
// `lib/database.types.ts` is generated by the Supabase CLI from the live
// schema, so it doesn't know about tables in migrations that haven't been
// pushed yet. Once migration 0010 lands and someone runs
//
//     supabase gen types typescript ... > lib/database.types.ts
//
// the augmentation here can be deleted and dispatch.ts can drop the cast.
// Until then, this gives the typed client enough shape information to
// validate inserts/updates against `signal_dispatches`.

import type { Database as BaseDatabase } from "@/lib/database.types";

export type SignalDispatchKind = "week-out" | "recap";
export type SignalDispatchStatus = "sent" | "failed" | "skipped";

export interface SignalDispatchRow {
  id: string;
  kind: SignalDispatchKind;
  key: string;
  group_id: string;
  status: SignalDispatchStatus;
  bridge_response: Record<string, unknown> | null;
  created_at: string;
}

export interface SignalDispatchInsert {
  id?: string;
  kind: SignalDispatchKind;
  key: string;
  group_id: string;
  status: SignalDispatchStatus;
  bridge_response?: Record<string, unknown> | null;
  created_at?: string;
}

export interface SignalDispatchUpdate {
  id?: string;
  kind?: SignalDispatchKind;
  key?: string;
  group_id?: string;
  status?: SignalDispatchStatus;
  bridge_response?: Record<string, unknown> | null;
  created_at?: string;
}

type BasePublic = BaseDatabase["public"];

export type DatabaseWithSignal = {
  __InternalSupabase: BaseDatabase["__InternalSupabase"];
  public: {
    Tables: BasePublic["Tables"] & {
      signal_dispatches: {
        Row: SignalDispatchRow;
        Insert: SignalDispatchInsert;
        Update: SignalDispatchUpdate;
        Relationships: [];
      };
    };
    Views: BasePublic["Views"];
    Functions: BasePublic["Functions"];
    Enums: BasePublic["Enums"];
    CompositeTypes: BasePublic["CompositeTypes"];
  };
};
