/**
 * Generated Supabase database types — placeholder.
 *
 * This file is auto-generated by the Supabase CLI once the project is linked
 * and the migration in `supabase/migrations/0001_initial_schema.sql` is
 * applied. Until then, this stub keeps the TS app compiling and the Supabase
 * helpers (`lib/supabase/{server,client}.ts`) generic-typed.
 *
 * To regenerate after applying the migration:
 *
 *   pnpm dlx supabase login
 *   pnpm dlx supabase link --project-ref <your-project-ref>
 *   pnpm dlx supabase gen types typescript --linked --schema public \
 *     > lib/database.types.ts
 *
 * Or against a local stack:
 *
 *   pnpm dlx supabase gen types typescript --local --schema public \
 *     > lib/database.types.ts
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
